version: "3"
services:
  nginx:
    image: nginx
    ports:
    - "443:443"
    - "8080:80"
    volumes:
    - "./nginx/nginx.conf:/usr/local/openresty/nginx/conf/nginx.conf"
    - "./nginx/cert/cert1.pem:/usr/local/openresty/nginx/conf/cert1.pem"
    - "./nginx/cert/privkey1.pem:/usr/local/openresty/nginx/conf/privkey1.pem"

  dns-server:
    image: dalongrong/doh-server
    build: 
      context: ./dns-server
      dockerfile: Dockerfile
  dns-proxy:
    image: dalongrong/dnscrypt-proxy
    build: 
      context: ./dns-proxy
      dockerfile: Dockerfile